using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Pirate.Shared.Shipyard;
using Content.Pirate.Shared.Shipyard.Prototypes;
using Content.Shared.Access.Systems;
using Content.Shared.Whitelist;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Pirate.Client.Shipyard;

[GenerateTypedNameReferences]
public sealed partial class ShipyardConsoleMenu : FancyWindow
{
    private readonly AccessReaderSystem _access;
    private readonly IPlayerManager _player;
    private readonly List<VesselPrototype> _vessels = [];
    private readonly List<VesselCategoryPrototype> _categories = [];
    private ProtoId<VesselCategoryPrototype>? _category;

    private const int AllCategoryId = 0;

    public event Action<string>? OnPurchased;
    public Entity<ShipyardConsoleComponent> Console;

    public ShipyardConsoleMenu(EntityUid console, IPrototypeManager proto, IEntityManager entMan,
        IPlayerManager player, AccessReaderSystem access, EntityWhitelistSystem whitelist)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Console = (console, entMan.GetComponent<ShipyardConsoleComponent>(console));
        _access = access;
        _player = player;

        foreach (var categoryId in Console.Comp.Categories)
        {
            if (proto.Resolve(categoryId, out var category))
                _categories.Add(category);
        }

        foreach (var vessel in proto.EnumeratePrototypes<VesselPrototype>())
        {
            if (!whitelist.IsWhitelistPassOrNull(vessel.Whitelist, console))
                continue;

            if (!vessel.Categories.Any(Console.Comp.Categories.Contains))
                continue;

            _vessels.Add(vessel);
        }

        _vessels.Sort((x, y) => string.Compare(Loc.GetString(x.Name), Loc.GetString(y.Name), StringComparison.CurrentCultureIgnoreCase));
        PopulateCategories();

        SearchBar.OnTextChanged += _ => PopulateProducts();
        Categories.OnItemSelected += args =>
        {
            if (args.Id == AllCategoryId)
            {
                _category = null;
                Categories.SelectId(AllCategoryId);
                PopulateProducts();
                return;
            }

            var categoryIndex = args.Id - 1;
            if (categoryIndex < 0 || categoryIndex >= _categories.Count)
                return;

            _category = _categories[categoryIndex];
            Categories.SelectId(args.Id);
            PopulateProducts();
        };

        PopulateProducts();
    }

    private void PopulateProducts()
    {
        Vessels.RemoveAllChildren();

        var access = _player.LocalSession?.AttachedEntity is { } player && _access.IsAllowed(player, Console);
        var search = SearchBar.Text.Trim();
        foreach (var vessel in _vessels)
        {
            if (search.Length != 0 && !Loc.GetString(vessel.Name).Contains(search, StringComparison.InvariantCultureIgnoreCase))
                continue;

            if (_category is { } category && !vessel.Categories.Contains(category.Id))
                continue;

            var row = new VesselRow(vessel, access, !Console.Comp.UseStationFunds);
            row.OnPurchasePressed += () => OnPurchased?.Invoke(vessel.ID);
            Vessels.AddChild(row);
        }
    }

    private void PopulateCategories()
    {
        Categories.Clear();
        Categories.AddItem(Loc.GetString("cargo-console-menu-populate-categories-all-text"), AllCategoryId);

        for (var i = 0; i < _categories.Count; i++)
            Categories.AddItem(_categories[i].LocalizedName, i + 1);

        _category = null;
        Categories.SelectId(AllCategoryId);
    }


    public void UpdateState(ShipyardConsoleState state)
    {
        BankAccountLabel.Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", state.Balance));
        PopulateProducts();
    }
}
