using Content.Pirate.Shared.Shipyard.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Pirate.Client.Shipyard;

[GenerateTypedNameReferences]
public sealed partial class VesselRow : PanelContainer
{
    public event Action? OnPurchasePressed;

    public VesselRow(VesselPrototype vessel, bool access = false, bool isFree = false)
    {
        RobustXamlLoader.Load(this);

        VesselName.Text = Loc.GetString(vessel.Name);
        var tooltip = new Tooltip();
        tooltip.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString(vessel.Description)));
        Purchase.TooltipSupplier = _ => tooltip;
        Purchase.Disabled = !access;
        Purchase.OnPressed += _ => OnPurchasePressed?.Invoke();
        Purchase.Text = isFree
            ? Loc.GetString("shipyard-console-price-free")
            : Loc.GetString("cargo-console-menu-points-amount", ("amount", vessel.Price));
    }
}
