// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Pinpointer.UI; // Goobstation
using Content.Client.Resources;
using Content.Client.UserInterface.Controls; // Goobstation
using Content.Shared._Pirate.ListeningPost; // Pirate: long range cameras
using Content.Shared._Pirate.ZLevels.Monitoring; // Pirate: multiz
using Content.Shared._DV.CCVars; // Pirate: accessibility no vision filters
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects; // Goobstation
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration; // Pirate
using Robust.Shared.Graphics;
using Robust.Shared.Map; // Goobstation
using Robust.Shared.Prototypes;
using Robust.Shared.Utility; // Goobstation

namespace Content.Client.SurveillanceCamera.UI;

[GenerateTypedNameReferences]
public sealed partial class SurveillanceCameraMonitorWindow : FancyWindow // Goobstation
{
    private static readonly ProtoId<ShaderPrototype> CameraStaticShader = "CameraStatic";
    private static readonly ProtoId<ShaderPrototype> SurveillanceVHSShader = "SurveillanceVHS"; // Pirate

    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private IEntityManager _entManager = default!; // Goobstation
    [Dependency] private readonly IConfigurationManager _configurationManager = default!; // Pirate

    public event Action<string>? CameraSelected;
    public event Action? CameraRefresh;
    public event Action? SubnetRefresh;
    public event Action? CameraSwitchTimer;
    public event Action? CameraDisconnect;
    public event Action<NetEntity?, int>? ZLevelSelected; // Pirate: multiz

    private string _currentAddress = string.Empty;
    private bool _isSwitching;
    private readonly FixedEye _defaultEye = new();
    private Action<bool>? _noVisionFiltersChanged; // Pirate: accessibility callback for the VHS overlay
    private readonly SpriteSystem _spriteSystem; // Goobstation
    private readonly Dictionary<NetEntity, string> _reverseCameras = new(); // Goobstation
    private readonly Dictionary<string, string> _resolveCameraName = new(); // Goobstation
    private Texture? _blipTexture; // Goobstation

    public SurveillanceCameraMonitorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entManager.System<SpriteSystem>(); // Goobstation

        // This could be done better. I don't want to deal with stylesheets at the moment.
        var texture = _resourceCache.GetTexture("/Textures/Interface/Nano/square_black.png");
        var shader = _prototypeManager.Index(CameraStaticShader).Instance().Duplicate();

        CameraView.ViewportSize = new Vector2i(770, 770);
        CameraView.Eye = _defaultEye; // sure
        CameraViewBackground.Stretch = TextureRect.StretchMode.Scale;
        CameraViewBackground.Texture = texture;
        CameraViewBackground.ShaderOverride = shader;

        // Pirate start: translucent VHS/CRT artifact overlay on the camera feed.
        // Ported from godotshaders.com/shader/vhs-and-crt-monitor-effect (CC0).
        // Rendered as an alpha-blended artifact layer over the feed; respects the
        // "Disable vision filters" accessibility option and is only shown while a
        // camera feed is connected.
        _noVisionFiltersChanged = v => UpdateVHSOverlay();
        _configurationManager.OnValueChanged(DCCVars.NoVisionFilters, _noVisionFiltersChanged, invokeImmediately: true);

        CameraViewVHS.Stretch = TextureRect.StretchMode.Scale;
        CameraViewVHS.Texture = texture;
        CameraViewVHS.ShaderOverride = _prototypeManager.Index(SurveillanceVHSShader).Instance().Duplicate();
        // Pirate end

        // Set trackable entity selected action - Camera Selection
        NavMap.TrackedEntitySelectedAction += SetTrackedEntityFromNavMap; // Goobstation

        SubnetRefreshButton.OnPressed += _ => SubnetRefresh!();
        CameraRefreshButton.OnPressed += _ => CameraRefresh!();
        CameraDisconnectButton.OnPressed += _ => CameraDisconnect!();
    }

    #region Pirate: accessibility for VHS overlay

    private bool _hasFeed;

    /// <summary>
    /// Shows the VHS overlay only while a camera feed is connected and the
    /// "Disable vision filters" accessibility option is off.
    /// </summary>
    private void UpdateVHSOverlay()
    {
        CameraViewVHS.Visible = _hasFeed && !_configurationManager.GetCVar(DCCVars.NoVisionFilters);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && _noVisionFiltersChanged != null)
            _configurationManager.UnsubValueChanged(DCCVars.NoVisionFilters, _noVisionFiltersChanged);

        base.Dispose(disposing);
    }

    #endregion

    // Goobstation start
    // need to translate entity to string and then call the same method the list does
    private void SetTrackedEntityFromNavMap(NetEntity? netEntity)
    {
        if (!netEntity.HasValue)
            return;

        CameraSelected!(_reverseCameras[netEntity.Value]);
    }

    public EntityUid Entity;

    // Needed for NavMap to initialize and draw the grid
    public void SetEntity(EntityUid uid)
    {
        Entity = uid;

        // Pass owner to nav map
        NavMap.Owner = uid;

        // Set nav map grid uid
        var stationName = Loc.GetString("surveillance-camera-monitor-ui-unknown-location");

        if (_entManager.TryGetComponent<TransformComponent>(uid, out var xform))
        {
            // Pirate: long range cameras - a remote console watches a station it is not standing on, the same
            // way a nuke operative handheld map targets a grid on another map.
            var displayedGrid = xform.GridUid;
            if (_entManager.TryGetComponent<LongRangeSurveillanceMonitorComponent>(uid, out var longRange))
                displayedGrid = longRange.TargetGrid;

            NavMap.MapUid = displayedGrid; // Pirate: long range cameras
            NavMap.ZLevelSelectorEnabled = true; // Pirate: multiz
            NavMap.ZFilterTrackedBlipsToDisplayedMap = true; // Pirate: multiz
            NavMap.SetZLevelSelectorRoot(displayedGrid); // Pirate: long range cameras
            NavMap.ZLevelSelectedAction += OnZLevelSelected; // Pirate: multiz

            // Assign station name
            if (_entManager.TryGetComponent<MetaDataComponent>(displayedGrid, out var stationMetaData)) // Pirate: long range cameras
                stationName = stationMetaData.EntityName;

            var msg = new FormattedMessage();
            msg.AddMarkupOrThrow(Loc.GetString("surveillance-camera-monitor-ui-station-name", ("stationName", stationName)));

            StationName.SetMessage(msg);
            _blipTexture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));
        }

        else
        {
            StationName.SetMessage(stationName);
            NavMap.Visible = false;
        }
    }

    #region Pirate: long range cameras
    private void RefreshRemoteTargetGrid()
    {
        if (NavMap.MapUid != null
            || !_entManager.TryGetComponent<LongRangeSurveillanceMonitorComponent>(Entity, out var longRange)
            || longRange.TargetGrid is not { } target)
        {
            return;
        }

        NavMap.MapUid = target;
        NavMap.SetZLevelSelectorRoot(target);
        NavMap.ForceNavMapUpdate();
        NavMap.Visible = true;

        if (!_entManager.TryGetComponent<MetaDataComponent>(target, out var stationMetaData))
            return;

        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("surveillance-camera-monitor-ui-station-name", ("stationName", stationMetaData.EntityName)));
        StationName.SetMessage(msg);
    }
    #endregion

    #region Pirate: multiz
    private void OnZLevelSelected(EntityUid gridUid, int depth)
    {
        ZLevelSelected?.Invoke(_entManager.GetNetEntity(gridUid), depth);
    }
    #endregion

    // Add a particular camera
    private void AddTrackedEntityToNavMap(NetEntity ent, NetCoordinates coordinates, bool selected, bool mobile)
    {
        if (!_entManager.TryGetEntity(coordinates.NetEntity, out var resolved) || // Pirate: syndicate remote monitoring
            !_entManager.HasComponent<TransformComponent>(resolved.Value)) // Pirate: syndicate remote monitoring - wait for remote camera entity state
        { // Pirate: syndicate remote monitoring
            QueuePendingBlip(ent, coordinates, selected, mobile); // Pirate: syndicate remote monitoring
            return; // Pirate: syndicate remote monitoring
        } // Pirate: syndicate remote monitoring

        var coords = _entManager.GetCoordinates(coordinates);
        var texture = new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_square.png"));
        var color = selected ? Color.Green : Color.Red;
        var blink = false;
        var modulator = Color.White;

        if (mobile)
            color = selected ? Color.Green : Color.Orange;
        else
            color = selected ? Color.Green : Color.Red;

        var blip = new NavMapBlip(coords, _spriteSystem.Frame0(texture), color * modulator, blink);
        NavMap.TrackedEntities[ent] = blip;
    }
    // Goobstation End

    // The UI class should get the eye from the entity, and then
    // pass it here so that the UI can change its view.
    public void UpdateState(IEye? eye, EntityUid? activeCamera, string activeAddress, Dictionary<string, (string, (NetEntity, NetCoordinates))> cameras, Dictionary<string, (string, (NetEntity, NetCoordinates))> mobileCameras, EntityUid monitor, EntityCoordinates? monitorCoords) // Pirate: multiz
    {
        _currentAddress = activeAddress;
        RefreshRemoteTargetGrid(); // Pirate: long range cameras
        CameraView.CEZLevelViewEntity = activeCamera; // Pirate: multiz
        SetCameraView(eye);
        // Goobstation start
        _reverseCameras.Clear();
        _resolveCameraName.Clear();
        NavMap.TrackedEntities.Clear();
        ClearPendingBlips(); // Pirate: syndicate remote monitoring
        foreach (var (camera, (name, (ent, coordinates))) in cameras)
        {
            _reverseCameras[ent] = camera;
            _resolveCameraName[camera] = name;
            AddTrackedEntityToNavMap(ent, coordinates, camera.Equals(_currentAddress) ? true : false, false);
        }
        foreach (var (camera, (name, (ent, coordinates))) in mobileCameras)
        {
            _reverseCameras[ent] = camera;
            _resolveCameraName[camera] = name;
            AddTrackedEntityToNavMap(ent, coordinates, camera.Equals(_currentAddress) ? true : false, true);
        }
        // Show monitor on nav map
        if (monitorCoords != null && _blipTexture != null)
            NavMap.TrackedEntities[_entManager.GetNetEntity(monitor)] = new NavMapBlip(monitorCoords.Value, _blipTexture, Color.Cyan, true, false);
        // Goobstation end
    }


    private void SetCameraView(IEye? eye)
    {
        var eyeChanged = eye != CameraView.Eye || CameraView.Eye == null;
        CameraView.Eye = eye ?? _defaultEye;
        CameraView.Visible = !eyeChanged && !_isSwitching;
        CameraDisconnectButton.Disabled = eye == null;
        _hasFeed = eye != null; // Pirate: VHS overlay only with a connected feed
        UpdateVHSOverlay(); // Pirate

        if (eye != null)
        {
            if (!eyeChanged)
            {
                return;
            }

            _isSwitching = true;
            CameraViewBackground.Visible = true;
            // Goobstation start
            if (_resolveCameraName.TryGetValue(_currentAddress, out var name))
                CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status",
                    ("status", Loc.GetString("surveillance-camera-monitor-ui-status-connecting")),
                    ("address", _currentAddress)) + " - " + name;
            else
                CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status",
                    ("status", Loc.GetString("surveillance-camera-monitor-ui-status-connecting")),
                    ("address", _currentAddress));
            // Goobstation end
            CameraSwitchTimer!();
        }
        else
        {
            CameraViewBackground.Visible = true;
            CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status-disconnected");
        }
    }

    public void OnSwitchTimerComplete()
    {
        _isSwitching = false;
        CameraView.Visible = CameraView.Eye != _defaultEye;
        CameraViewBackground.Visible = CameraView.Eye == _defaultEye;
        _hasFeed = CameraView.Eye != _defaultEye; // Pirate
        UpdateVHSOverlay(); // Pirate
        // Goobstation start
        if (_resolveCameraName.TryGetValue(_currentAddress, out var name))
            CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status",
                            ("status", Loc.GetString("surveillance-camera-monitor-ui-status-connected")),
                            ("address", _currentAddress)) + " - " + name;
        else
            CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status",
                            ("status", Loc.GetString("surveillance-camera-monitor-ui-status-connected")),
                            ("address", _currentAddress));
        // Goobstation end
    }
}
