# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: HecuOperative
  name: job-name-hecu
  description: job-description-hecu
  playTimeTracker: JobHecuOperative
  # Pirate: HECU rework start
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipERT
  # Pirate: HECU rework end
  setPreference: false
  startingGear: HECUOperativeGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - NanotrasenRepresentative
  - BlueshieldOfficer

- type: startingGear
  id: HECUOperativeGear
  # Pirate: HECU IPC squad - shares gear with the human squad through its base role.
  parent: HECUSquadGearHuman # Pirate: HECU IPC squad
  inhand:
  - WeaponRifleM16 # Pirate: HECU rework
