// SPDX-FileCopyrightText: 2026 SpaceStationUA
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.Administration.UI.BanList.ChatBans;

[GenerateTypedNameReferences]
public sealed partial class ChatBanListHeader : ContainerButton
{
    public ChatBanListHeader()
    {
        RobustXamlLoader.Load(this);
    }
}
