// SPDX-FileCopyrightText: 2026 SpaceStationUA
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Administration.BanList;
using Content.Client.Administration.UI.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.Administration.UI.BanList.ChatBans;

[GenerateTypedNameReferences]
public sealed partial class ChatBanListControl : Control
{
    public event Action<ChatBanListLine>? LineIdsClicked;
    public event Action<ChatBanListLine>? UnbanClicked;

    public ChatBanListControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetChatBans(List<SharedBan> bans)
    {
        for (var i = ChatBans.ChildCount - 1; i >= 1; i--)
            ChatBans.RemoveChild(ChatBans.GetChild(i));

        foreach (var ban in bans)
        {
            ChatBans.AddChild(new HSeparator());
            var line = new ChatBanListLine(ban);
            line.IdsClicked += value => LineIdsClicked?.Invoke(value);
            line.UnbanClicked += value => UnbanClicked?.Invoke(value);
            ChatBans.AddChild(line);
        }
    }
}
