// SPDX-FileCopyrightText: 2026 SpaceStationUA
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Administration.UI.BanList;
using Content.Shared.Administration.BanList;
using Content.Shared.Database;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.Administration.UI.BanList.ChatBans;

[GenerateTypedNameReferences]
public sealed partial class ChatBanListLine : BoxContainer, IBanListLine<SharedBan>
{
    private bool _confirmUnban;

    public SharedBan Ban { get; }
    public event Action<ChatBanListLine>? IdsClicked;
    public event Action<ChatBanListLine>? UnbanClicked;

    public ChatBanListLine(SharedBan ban)
    {
        RobustXamlLoader.Load(this);
        Ban = ban;
        Channel.Text = ban.Type switch
        {
            BanType.OOC => Loc.GetString("chat-ban-channel-ooc"),
            BanType.LOOC => Loc.GetString("chat-ban-channel-looc"),
            BanType.Deadchat => Loc.GetString("chat-ban-channel-deadchat"),
            _ => ban.Type.ToString(),
        };
        UnbanButton.Visible = ban.Unban == null &&
                              (ban.ExpirationTime == null || ban.ExpirationTime > DateTime.UtcNow);
        IdsHidden.OnPressed += _ => IdsClicked?.Invoke(this);
        UnbanButton.OnPressed += _ => OnUnbanPressed();
        BanListEui.SetData(this, ban);
    }

    private void OnUnbanPressed()
    {
        if (!_confirmUnban)
        {
            _confirmUnban = true;
            UnbanButton.Text = Loc.GetString("chat-ban-list-unban-confirm");
            UnbanButton.ModulateSelfOverride = Color.Red;
            return;
        }

        UnbanButton.Disabled = true;
        UnbanClicked?.Invoke(this);
    }
}
