// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Text;
using Content.Shared._Pirate.NanoChatMonitor;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Pirate.NanoChatMonitor;

[GenerateTypedNameReferences]
public sealed partial class NanoChatMonitorConversationEntry : ContainerButton
{
    private static readonly Color SelectedEntryColor = Color.FromHex("#4d5478d9");
    private static readonly Color ActiveIndicatorColor = Color.FromHex("#7ea2ff");

    public ulong ConversationKey { get; private set; }

    public NanoChatMonitorConversationEntry()
    {
        RobustXamlLoader.Load(this);
    }

    public static string BuildSearchText(NanoChatMonitorConversationSummary summary)
    {
        var builder = new StringBuilder();

        builder.Append(summary.NameA);
        builder.Append(' ');
        builder.Append(summary.NameB);
        builder.Append(' ');
        builder.Append(summary.JobA);
        builder.Append(' ');
        builder.Append(summary.JobB);
        builder.Append(' ');
        // Numbers arrive pre-formatted, so a redacted one is not searchable
        // by anything but the redaction marker itself. The unpadded form is added so "42" still finds
        // #0042.
        builder.Append(summary.NumberA);
        builder.Append(' ');
        builder.Append(summary.NumberA.TrimStart('0'));
        builder.Append(' ');
        builder.Append(summary.NumberB);
        builder.Append(' ');
        builder.Append(summary.NumberB.TrimStart('0'));

        return builder.ToString().ToLowerInvariant();
    }

    public void Update(NanoChatMonitorConversationSummary summary, TimeSpan lastStationTime, bool selected)
    {
        ConversationKey = summary.Key;

        Describe(FirstParticipantLabel, summary.NameA, summary.JobA, summary.NumberA);
        Describe(SecondParticipantLabel, summary.NameB, summary.JobB, summary.NumberB);

        TimeLabel.Text = Loc.GetString("nanochat-monitor-conversation-last",
            ("time", lastStationTime.ToString(@"hh\:mm\:ss")));

        SetSelected(selected);
    }

    public void SetSelected(bool selected)
    {
        Pressed = selected;
        ModulateSelfOverride = selected ? SelectedEntryColor : null;

        if (SelectionIndicator.PanelOverride is not StyleBoxFlat indicator)
            return;

        var color = selected ? ActiveIndicatorColor : Color.Transparent;
        indicator.BackgroundColor = color;
        indicator.BorderColor = color;
    }

    /// <remarks>
    ///     Job titles wrap rather than truncate, and numbers are already formatted so a redacted
    ///     participant cannot be reconstructed here.
    /// </remarks>
    private static void Describe(RichTextLabel label, string name, string? job, string number4)
    {
        name = FormattedMessage.EscapeText(name);
        job = job is null ? null : FormattedMessage.EscapeText(job);

        label.Text = string.IsNullOrWhiteSpace(job)
            ? Loc.GetString("nanochat-monitor-conversation-participant", ("name", name), ("number", number4))
            : Loc.GetString("nanochat-monitor-conversation-participant-job",
                ("name", name),
                ("number", number4),
                ("job", job));
    }
}
