// SPDX-License-Identifier: AGPL-3.0-or-later

using System.IO;
using System.Numerics;
using Content.Shared._Pirate.NanoChatMonitor;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Pirate.NanoChatMonitor;

[GenerateTypedNameReferences]
public sealed partial class NanoChatMonitorMessageRow : BoxContainer
{
    private static readonly Color LeftBubbleColor = Color.FromHex("#3b4258f0");
    private static readonly Color RightBubbleColor = Color.FromHex("#1f402fd9");
    private static readonly Color TextColor = Color.FromHex("#e1e6f0");
    private static readonly Color SubTextColor = Color.FromHex("#9ca6c2");

    private const float MaxPhotoSize = 400f;

    public event Action<string>? OnPrintPhoto;

    public string? AttachmentId { get; private set; }

    private bool? _renderedOnRight;

    public NanoChatMonitorMessageRow()
    {
        RobustXamlLoader.Load(this);

        ContentLabel.Modulate = TextColor;
        PhotoNameLabel.ModulateSelfOverride = TextColor.WithAlpha(0.8f);
        SenderLabel.ModulateSelfOverride = SubTextColor;
        LocationLabel.ModulateSelfOverride = TextColor.WithAlpha(0.55f);

        PrintPhotoButton.OnPressed += _ =>
        {
            if (AttachmentId != null)
                OnPrintPhoto?.Invoke(AttachmentId);
        };
    }

    public void Update(NanoChatMonitorLogEntry entry, bool onRight, bool showSender)
    {
        if (MessagePanel.PanelOverride is StyleBoxFlat style)
        {
            style.BackgroundColor = onRight ? RightBubbleColor : LeftBubbleColor;
            style.BorderThickness = new Thickness(0);
        }

        SenderLabel.Visible = showSender;
        if (showSender)
        {
            SenderLabel.Text = Loc.GetString("nanochat-monitor-entry-sender",
                ("name", entry.SenderName),
                ("number", entry.SenderNumber), // formatted server side.
                ("job", entry.SenderJob ?? Loc.GetString("nanochat-monitor-no-job")));
            SenderLabel.HorizontalAlignment = onRight ? HAlignment.Right : HAlignment.Left;
        }

        LocationLabel.Text = Loc.GetString("nanochat-monitor-entry-location", ("location", entry.Location));

        var hasText = !string.IsNullOrWhiteSpace(entry.Content);
        ContentLabel.Visible = hasText;
        ContentLabel.Text = hasText ? entry.Content : string.Empty;

        AttachmentId = entry.AttachmentId;

        PhotoNameLabel.Visible = AttachmentId != null;
        PrintPhotoButton.Visible = AttachmentId != null;
        PhotoNameLabel.Text = entry.AttachmentName ?? string.Empty;

        Photo.Texture = null;
        Photo.Visible = false;
        PhotoLoadingLabel.Visible = AttachmentId != null;

        UpdateSide(onRight);
    }

    public void SetPhoto(NanoChatMonitorAttachmentMessage attachment, Texture? texture)
    {
        if (AttachmentId != attachment.AttachmentId)
            return;

        Photo.Texture = texture;
        Photo.Visible = texture != null;
        PhotoLoadingLabel.Visible = texture == null;
        PhotoLoadingLabel.Text = Loc.GetString("nanochat-monitor-photo-unavailable");

        if (texture == null)
            return;

        var width = (float) texture.Size.X;
        var height = (float) texture.Size.Y;

        if (width <= 0 || height <= 0)
            return;

        var scale = Math.Min(1f, Math.Min(MaxPhotoSize / width, MaxPhotoSize / height));
        Photo.SetSize = new Vector2(width * scale, height * scale);

        if (!string.IsNullOrWhiteSpace(attachment.Caption))
            PhotoNameLabel.Text = $"{attachment.FileName} - {attachment.Caption}";
    }

    private void UpdateSide(bool onRight)
    {
        if (_renderedOnRight == onRight)
            return;

        MessageContainer.RemoveAllChildren();

        if (onRight)
        {
            MessageContainer.AddChild(FlexSpace);
            MessageContainer.AddChild(MessageBox);
            MessageContainer.AddChild(RightSpacer);
        }
        else
        {
            MessageContainer.AddChild(LeftSpacer);
            MessageContainer.AddChild(MessageBox);
            MessageContainer.AddChild(FlexSpace);
        }

        _renderedOnRight = onRight;
    }

    public static Texture? LoadTexture(byte[]? data, string id)
    {
        if (data is not { Length: > 0 })
            return null;

        try
        {
            using var stream = new MemoryStream(data);
            return Texture.LoadFromPNGStream(stream, $"nanochat-monitor-photo-{id}");
        }
        catch (Exception)
        {
            return null;
        }
    }
}
